server {
  listen 80;
  server_name walletapp.top localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    # If a file is not found, serve index.html
    try_files $uri $uri/ /index.html;
  }
}
