"""Initial migration

Revision ID: 48212994a09f
Revises: 12a05d6df7aa
Create Date: 2025-03-03 14:40:29.894997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48212994a09f'
down_revision: Union[str, None] = '12a05d6df7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_analysis', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('bill_id', sa.String(), nullable=True),
    sa.Column('payee', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('forecast_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_forecast_bill_id'), 'bill_forecast', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_forecast_id'), 'bill_forecast', ['id'], unique=False)
    op.create_index(op.f('ix_bill_forecast_user_id'), 'bill_forecast', ['user_id'], unique=False)
    op.create_table('budget_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('budget_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('budgeted', sa.Float(), nullable=True),
    sa.Column('spent', sa.Float(), nullable=True),
    sa.Column('remaining', sa.Float(), nullable=True),
    sa.Column('percentage_used', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_analysis_budget_id'), 'budget_analysis', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_analysis_id'), 'budget_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_budget_analysis_user_id'), 'budget_analysis', ['user_id'], unique=False)
    op.create_table('cash_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('expenses', sa.Float(), nullable=True),
    sa.Column('net', sa.Float(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('period_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_id'), 'cash_flow', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flow_user_id'), 'cash_flow', ['user_id'], unique=False)
    op.create_table('dashboard_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('total_balance', sa.Float(), nullable=True),
    sa.Column('month_income', sa.Float(), nullable=True),
    sa.Column('month_expenses', sa.Float(), nullable=True),
    sa.Column('month_savings', sa.Float(), nullable=True),
    sa.Column('savings_rate', sa.Float(), nullable=True),
    sa.Column('prev_month_income', sa.Float(), nullable=True),
    sa.Column('prev_month_expenses', sa.Float(), nullable=True),
    sa.Column('prev_month_savings', sa.Float(), nullable=True),
    sa.Column('income_change', sa.Float(), nullable=True),
    sa.Column('spending_change', sa.Float(), nullable=True),
    sa.Column('net_change', sa.Float(), nullable=True),
    sa.Column('avg_daily_spending', sa.Float(), nullable=True),
    sa.Column('days_tracked', sa.Integer(), nullable=True),
    sa.Column('upcoming_bills_total', sa.Float(), nullable=True),
    sa.Column('paid_bills_total', sa.Float(), nullable=True),
    sa.Column('largest_expense_category', sa.String(), nullable=True),
    sa.Column('largest_expense_amount', sa.Float(), nullable=True),
    sa.Column('top_categories', sa.JSON(), nullable=True),
    sa.Column('top_income_sources', sa.JSON(), nullable=True),
    sa.Column('spending_by_day', sa.JSON(), nullable=True),
    sa.Column('spending_trends', sa.JSON(), nullable=True),
    sa.Column('income_trends', sa.JSON(), nullable=True),
    sa.Column('monthly_avg_income', sa.Float(), nullable=True),
    sa.Column('monthly_avg_spending', sa.Float(), nullable=True),
    sa.Column('income_stability', sa.Float(), nullable=True),
    sa.Column('goals_on_track', sa.Integer(), nullable=True),
    sa.Column('goals_at_risk', sa.Integer(), nullable=True),
    sa.Column('total_goals', sa.Integer(), nullable=True),
    sa.Column('total_budgets', sa.Integer(), nullable=True),
    sa.Column('total_budgeted', sa.Float(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_stats_id'), 'dashboard_stats', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_stats_user_id'), 'dashboard_stats', ['user_id'], unique=False)
    op.create_table('goal_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('projected_completion_date', sa.DateTime(), nullable=True),
    sa.Column('on_track', sa.Boolean(), nullable=True),
    sa.Column('percentage_complete', sa.Float(), nullable=True),
    sa.Column('recommended_monthly_contribution', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('predicted_income', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('prediction_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'TIP', 'OPPORTUNITY', name='insighttype'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spending_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('predicted_spending', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('prediction_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spending_predictions')
    op.drop_table('insights')
    op.drop_table('income_predictions')
    op.drop_table('goal_projections')
    op.drop_index(op.f('ix_dashboard_stats_user_id'), table_name='dashboard_stats')
    op.drop_index(op.f('ix_dashboard_stats_id'), table_name='dashboard_stats')
    op.drop_table('dashboard_stats')
    op.drop_index(op.f('ix_cash_flow_user_id'), table_name='cash_flow')
    op.drop_index(op.f('ix_cash_flow_id'), table_name='cash_flow')
    op.drop_table('cash_flow')
    op.drop_index(op.f('ix_budget_analysis_user_id'), table_name='budget_analysis')
    op.drop_index(op.f('ix_budget_analysis_id'), table_name='budget_analysis')
    op.drop_index(op.f('ix_budget_analysis_budget_id'), table_name='budget_analysis')
    op.drop_table('budget_analysis')
    op.drop_index(op.f('ix_bill_forecast_user_id'), table_name='bill_forecast')
    op.drop_index(op.f('ix_bill_forecast_id'), table_name='bill_forecast')
    op.drop_index(op.f('ix_bill_forecast_bill_id'), table_name='bill_forecast')
    op.drop_table('bill_forecast')
    op.drop_table('analysis_jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
