server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.boot.web: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost"
              - "https://walletapp.top"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true

      routes:
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:user-service.wallet.svc.cluster.local}
          predicates:
            - Path=/api/v1/user/**
        - id: finance-service
          uri: http://${FINANCE_SERVICE_BASEURL:finance-service.wallet.svc.cluster.local}
          predicates:
            - Path=/api/v1/finance/**
        - id: insights-service
          uri: http://${INSIGHTS_SERVICE_BASEURL:insights-service.wallet.svc.cluster.local}
          predicates:
            - Path=/api/v1/insights/**