apiVersion: v1
kind: Secret
metadata:
    name: wallet-secrets
    namespace: wallet
type: Opaque
stringData:
    DB_ROOT_PASSWORD: "YOUR_DB_ROOT_PASSWORD"
    USER_DB_USER: "YOUR_USER_DB_USER"
    USER_DB_PASS: "YOUR_USER_DB_PASS"
    INSIGHTS_DB_USER: "YOUR_DB_USER"
    INSIGHTS_DB_PASS: "YOUR_DB_PASSWORD"
    POSTGRES_URI: "postgresql://YOUR_USER_DB_USER:YOUR_USER_DB_PASS@insights-db-svc:5432/wallet"
    GOOGLE_CLIENT_ID: "YOUR_GOOGLE_CLIENT_ID"
    GOOGLE_CLIENT_SECRET: "YOUR_GOOGLE_CLIENT_SECRET"
