apiVersion: v1
kind: Service
metadata:
    name: user-service
    namespace: wallet
    labels:
        app: user-service
spec:
    ports:
        - port: 8081
          targetPort: 8081
          name: http
    selector:
        app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service
    namespace: wallet
spec:
    selector:
        matchLabels:
            app: user-service
    replicas: 1
    template:
        metadata:
            labels:
                app: user-service
        spec:
            containers:
                - name: user-service
                  image: ahm282/user-service:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8081
                  env:
                      - name: USER_DB_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: wallet-config
                                key: USER_DB_HOST
                      - name: USER_DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: wallet-config
                                key: USER_DB_PORT
                      - name: USER_DB_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: wallet-config
                                key: USER_DB_NAME
                      - name: USER_DB_USER
                        valueFrom:
                            secretKeyRef:
                                name: wallet-secrets
                                key: USER_DB_USER
                      - name: USER_DB_PASS
                        valueFrom:
                            secretKeyRef:
                                name: wallet-secrets
                                key: USER_DB_PASS
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
